import type { RouteMetadata } from "../services/ai/apiRegistry.js"

export const ADMIN_ROUTE_METADATA: RouteMetadata[] = [
  { method: "GET", path: "/api/v1/admin/cron/status", description: "获取所有定时任务状态（新闻抓取、摘要、预测）" },
  { method: "GET", path: "/api/v1/admin/models", description: "获取可用 AI 模型列表" },
  { method: "POST", path: "/api/v1/admin/cron/trigger/fetch", description: "手动触发新闻抓取任务" },
  { method: "POST", path: "/api/v1/admin/cron/trigger/digest", description: "手动触发新闻摘要任务" },
  { method: "POST", path: "/api/v1/admin/cron/trigger/prediction", description: "手动触发预测任务" },
  { method: "POST", path: "/api/v1/admin/cron/abort/:taskType", description: "中止指定类型的定时任务" },
  { method: "GET", path: "/api/v1/admin/digest-logs", description: "获取摘要任务日志（分页，支持状态筛选）" },
  { method: "GET", path: "/api/v1/admin/tables", description: "获取所有数据库表名及记录数" },
  { method: "GET", path: "/api/v1/admin/tables/:table", description: "查询指定表的数据（分页、排序、筛选）" },
  { method: "GET", path: "/api/v1/admin/tables/:table/:field", description: "获取指定表某字段的唯一值列表" },
  { method: "POST", path: "/api/v1/admin/tables/:table", description: "高级查询指定表（支持复杂 where 条件）" },
  { method: "POST", path: "/api/v1/admin/chat/stream", description: "管理后台 AI 聊天流式接口（SSE）", aiExclude: true },
  { method: "GET", path: "/api/v1/admin/chat/sessions", description: "获取管理后台聊天会话列表" },
  { method: "GET", path: "/api/v1/admin/chat/sessions/:id", description: "获取管理后台指定会话详情" },
  { method: "DELETE", path: "/api/v1/admin/chat/sessions/:id", description: "删除管理后台聊天会话" },
  { method: "GET", path: "/api/v1/admin/news-sources", description: "获取所有新闻源配置" },
  { method: "GET", path: "/api/v1/admin/news-fetch-logs", description: "获取新闻抓取日志（分页）" },
  { method: "POST", path: "/api/v1/admin/news-sources", description: "新增新闻源" },
  { method: "PUT", path: "/api/v1/admin/news-sources/:id", description: "更新新闻源配置" },
  { method: "DELETE", path: "/api/v1/admin/news-sources/:id", description: "删除新闻源" },
  { method: "POST", path: "/api/v1/admin/news-sources/:id/test", description: "测试新闻源抓取" },
  { method: "GET", path: "/api/v1/admin/market-data/ohlc", description: "获取 OHLC 市场数据（支持 symbol/days/interval）" },
  { method: "POST", path: "/api/v1/admin/indicator-configs/preview-formula", description: "预览公式计算结果" },
  { method: "GET", path: "/api/v1/admin/indicator-groups", description: "获取指标分组列表" },
  { method: "POST", path: "/api/v1/admin/indicator-groups", description: "创建指标分组" },
  { method: "PUT", path: "/api/v1/admin/indicator-groups/:id", description: "更新指标分组" },
  { method: "DELETE", path: "/api/v1/admin/indicator-groups/:id", description: "删除指标分组" },
  { method: "GET", path: "/api/v1/admin/indicator-configs", description: "获取所有指标配置" },
  { method: "PUT", path: "/api/v1/admin/indicator-configs/:id", description: "更新指标配置" },
  { method: "POST", path: "/api/v1/admin/indicator-configs", description: "创建新指标配置" },
  { method: "DELETE", path: "/api/v1/admin/indicator-configs/:id", description: "删除指标配置" },
  { method: "POST", path: "/api/v1/admin/indicator-configs/validate-formula", description: "验证指标公式语法" },
  { method: "POST", path: "/api/v1/admin/indicator-configs/validate-step-formulas", description: "验证多步骤公式" },
  { method: "GET", path: "/api/v1/admin/indicator-categories", description: "获取指标分类列表" },
  { method: "GET", path: "/api/v1/admin/cron/latest-output/:taskType", description: "获取指定任务最近一次输出" },
  { method: "GET", path: "/api/v1/admin/predictions/timeline", description: "获取预测时间线（管理视图）" },
  { method: "GET", path: "/api/v1/admin/predictions/:id", description: "获取单条预测详情（管理视图）" },
]
